[package]
name = "substrate-test-utils"
version = "3.0.0"
license = "Apache-2.0"
description = "Substrate test utilities"
publish = false

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
