[package]
name = "sc-executor-common"
version = "0.41.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "A set of common definitions that are needed for defining execution engines."
documentation = "https://docs.rs/sc-executor-common/"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.polkavm]
workspace = true
optional = true

[dependencies.sc-allocator]
default-features = true
workspace = true

[dependencies.sp-wasm-interface]
default-features = true
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.wasm-instrument]
workspace = true
default-features = true

[features]
default = []
