[package]
name = "substrate-rpc-client"
version = "0.49.0"
license = "Apache-2.0"
description = "Shared JSON-RPC client"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.jsonrpsee]
features = ["ws-client"]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.sc-rpc-api]
default-features = true
workspace = true

[dependencies.serde]
workspace = true
default-features = true

[dependencies.sp-runtime]
default-features = true
workspace = true
