[package]
name = "pallet-safe-mode"
version = "21.1.0"
license = "Apache-2.0"
description = "FRAME safe-mode pallet"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true

[dependencies.docify]
workspace = true

[dependencies.frame-benchmarking]
optional = true
workspace = true

[dependencies.frame-support]
workspace = true

[dependencies.frame-system]
workspace = true

[dependencies.pallet-balances]
optional = true
workspace = true

[dependencies.pallet-proxy]
optional = true
workspace = true

[dependencies.pallet-utility]
optional = true
workspace = true

[dependencies.scale-info]
features = ["derive"]
workspace = true

[dependencies.sp-arithmetic]
workspace = true

[dependencies.sp-runtime]
workspace = true

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-balances?/std",
    "pallet-proxy?/std",
    "pallet-utility?/std",
    "scale-info/std",
    "sp-arithmetic/std",
    "sp-runtime/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-proxy/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
    "pallet-balances?/try-runtime",
    "pallet-proxy?/try-runtime",
    "pallet-utility?/try-runtime",
    "sp-runtime/try-runtime",
]
