[package]
name = "sc-service"
version = "0.60.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Substrate service. Starts a thread that spins up the network, client, and extrinsic pool. Manages communication between them."
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.codec]
workspace = true
default-features = true

[dependencies.directories]
workspace = true

[dependencies.exit-future]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.futures-timer]
workspace = true

[dependencies.jsonrpsee]
features = ["server"]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.parking_lot]
workspace = true
default-features = true

[dependencies.pin-project]
workspace = true

[dependencies.prometheus-endpoint]
workspace = true
default-features = true

[dependencies.rand]
workspace = true
default-features = true

[dependencies.sc-chain-spec]
workspace = true
default-features = true

[dependencies.sc-client-api]
workspace = true
default-features = true

[dependencies.sc-client-db]
workspace = true

[dependencies.sc-consensus]
workspace = true
default-features = true

[dependencies.sc-executor]
workspace = true
default-features = true

[dependencies.sc-informant]
workspace = true
default-features = true

[dependencies.sc-keystore]
workspace = true
default-features = true

[dependencies.sc-network]
workspace = true
default-features = true

[dependencies.sc-network-common]
workspace = true
default-features = true

[dependencies.sc-network-sync]
workspace = true
default-features = true

[dependencies.sc-network-transactions]
workspace = true
default-features = true

[dependencies.sc-network-types]
workspace = true
default-features = true

[dependencies.sc-rpc]
workspace = true
default-features = true

[dependencies.sc-rpc-server]
workspace = true
default-features = true

[dependencies.sc-sysinfo]
workspace = true
default-features = true

[dependencies.sc-telemetry]
workspace = true
default-features = true

[dependencies.sc-tracing]
workspace = true
default-features = true

[dependencies.sc-transaction-pool]
workspace = true
default-features = true

[dependencies.sc-transaction-pool-api]
workspace = true
default-features = true

[dependencies.sc-utils]
workspace = true
default-features = true

[dependencies.schnellru]
workspace = true

[dependencies.serde]
workspace = true
default-features = true

[dependencies.serde_json]
workspace = true
default-features = true

[dependencies.sp-api]
workspace = true
default-features = true

[dependencies.sp-blockchain]
workspace = true
default-features = true

[dependencies.sp-consensus]
workspace = true
default-features = true

[dependencies.sp-core]
workspace = true
default-features = true

[dependencies.sp-externalities]
workspace = true
default-features = true

[dependencies.sp-keystore]
workspace = true
default-features = true

[dependencies.sp-runtime]
workspace = true
default-features = true

[dependencies.sp-session]
workspace = true
default-features = true

[dependencies.sp-state-machine]
workspace = true
default-features = true

[dependencies.sp-storage]
workspace = true
default-features = true

[dependencies.sp-transaction-pool]
workspace = true
default-features = true

[dependencies.sp-trie]
workspace = true
default-features = true

[dependencies.sp-version]
workspace = true
default-features = true

[dependencies.tempfile]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tokio]
features = [
    "parking_lot",
    "rt-multi-thread",
    "time",
]
workspace = true
default-features = true

[dependencies.tracing]
workspace = true
default-features = true

[dependencies.tracing-futures]
workspace = true

[features]
default = ["rocksdb"]
rocksdb = ["sc-client-db/rocksdb"]
runtime-benchmarks = [
    "sc-client-db/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]
jemalloc-allocator = ["sc-client-db/jemalloc-allocator"]
