[package]
description = "Substrate transaction protocol"
name = "sc-network-transactions"
version = "0.57.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
documentation = "https://docs.rs/sc-network-transactions"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.array-bytes]
workspace = true
default-features = true

[dependencies.codec]
features = ["derive"]
workspace = true
default-features = true

[dependencies.futures]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.prometheus-endpoint]
workspace = true
default-features = true

[dependencies.sc-network]
workspace = true
default-features = true

[dependencies.sc-network-common]
workspace = true
default-features = true

[dependencies.sc-network-sync]
workspace = true
default-features = true

[dependencies.sc-network-types]
workspace = true
default-features = true

[dependencies.sc-utils]
workspace = true
default-features = true

[dependencies.sp-consensus]
workspace = true
default-features = true

[dependencies.sp-runtime]
workspace = true
default-features = true
