[package]
name = "pallet-transaction-payment-rpc"
version = "43.0.0"
license = "Apache-2.0"
description = "RPC interface for the transaction payment pallet."
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.codec]
workspace = true
default-features = true

[dependencies.jsonrpsee]
features = [
    "client-core",
    "macros",
    "server-core",
]
workspace = true

[dependencies.pallet-transaction-payment-rpc-runtime-api]
default-features = true
workspace = true

[dependencies.sp-api]
default-features = true
workspace = true

[dependencies.sp-blockchain]
default-features = true
workspace = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.sp-rpc]
default-features = true
workspace = true

[dependencies.sp-runtime]
default-features = true
workspace = true

[dependencies.sp-weights]
default-features = true
workspace = true
