[package]
name = "void"
version = "1.0.99"
description = "void shim with std::convert::Infallible"
license = "MIT"
repository = "https://github.com/serai-dex/patch-polkadot-sdk/tree/develop/void"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2018"
rust-version = "1.34"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
