[package]
name = "sp-weights"
version = "32.0.0"
license = "Apache-2.0"
description = "Types and traits for interfacing between the host and the wasm runtime."
documentation = "https://docs.rs/sp-wasm-interface"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.bounded-collections]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true

[dependencies.serde]
optional = true
features = [
    "alloc",
    "derive",
]
workspace = true

[dependencies.smallvec]
workspace = true
default-features = true

[dependencies.sp-arithmetic]
workspace = true

[dependencies.sp-debug-derive]
workspace = true

[features]
default = ["std"]
std = [
    "bounded-collections/std",
    "codec/std",
    "serde/std",
    "sp-arithmetic/std",
    "sp-debug-derive/std",
]
serde = [
    "bounded-collections/serde",
    "dep:serde",
    "sp-arithmetic/serde",
]
json-schema = []
