[package]
name = "sp-arithmetic"
version = "28.0.1"
license = "Apache-2.0"
description = "Minimal fixed point arithmetic primitives and types for runtime."
documentation = "https://docs.rs/sp-arithmetic"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.codec]
features = [
    "derive",
    "max-encoded-len",
]
workspace = true

[dependencies.num-traits]
workspace = true

[dependencies.serde]
features = [
    "alloc",
    "derive",
]
optional = true
workspace = true

[dependencies.static_assertions]
workspace = true
default-features = true

[features]
default = ["std"]
std = [
    "codec/std",
    "num-traits/std",
    "serde/std",
]
serde = ["dep:serde"]
