[package]
name = "sc-authority-discovery"
version = "0.59.0"
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Substrate authority discovery."
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.codec]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.futures-timer]
workspace = true

[dependencies.ip_network]
workspace = true

[dependencies.linked_hash_set]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.prometheus-endpoint]
workspace = true
default-features = true

[dependencies.prost]
workspace = true

[dependencies.rand]
workspace = true
default-features = true

[dependencies.sc-network]
workspace = true
default-features = true

[dependencies.sc-network-types]
workspace = true
default-features = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.sp-api]
workspace = true
default-features = true

[dependencies.sp-authority-discovery]
workspace = true
default-features = true

[dependencies.sp-blockchain]
workspace = true
default-features = true

[dependencies.sp-core]
workspace = true
default-features = true

[dependencies.sp-keystore]
workspace = true
default-features = true

[dependencies.sp-runtime]
workspace = true
default-features = true

[dependencies.thiserror]
workspace = true

[dependencies.tokio]
workspace = true

[build-dependencies.prost-build]
workspace = true
