[package]
name = "sp-runtime"
version = "46.0.0"
license = "Apache-2.0"
description = "Runtime Modules shared primitive types."
documentation = "https://docs.rs/sp-runtime"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.bytes]
workspace = true

[dependencies.codec]
features = [
    "derive",
    "max-encoded-len",
]
workspace = true

[dependencies.either]
workspace = true

[dependencies.fnv]
version = "1"
default-features = false

[dependencies.impl-trait-for-tuples]
workspace = true

[dependencies.log]
workspace = true

[dependencies.paste]
workspace = true
default-features = true

[dependencies.rand]
optional = true
workspace = true
default-features = true

[dependencies.serde]
features = [
    "alloc",
    "derive",
]
optional = true
workspace = true

[dependencies.sp-application-crypto]
workspace = true

[dependencies.sp-arithmetic]
workspace = true

[dependencies.sp-core]
workspace = true

[dependencies.sp-io]
workspace = true

[dependencies.sp-trie]
workspace = true

[dependencies.sp-weights]
workspace = true

[dependencies.strum]
workspace = true
features = ["derive"]

[dependencies.tuplex]
workspace = true
default-features = false

[features]
runtime-benchmarks = []
try-runtime = []
default = ["std"]
std = [
    "bytes/std",
    "codec/std",
    "either/std",
    "either/use_std",
    "log/std",
    "rand",
    "serde/std",
    "sp-application-crypto/std",
    "sp-arithmetic/std",
    "sp-core/std",
    "sp-io/std",
    "sp-trie/std",
    "sp-weights/std",
    "strum/std",
    "tuplex/std",
]
serde = [
    "dep:serde",
    "sp-application-crypto/serde",
    "sp-arithmetic/serde",
    "sp-core/serde",
    "sp-weights/serde",
]
