[package]
name = "sp-debug-derive"
version = "14.0.0"
license = "Apache-2.0"
description = "Macros to derive runtime debug implementation."
documentation = "https://docs.rs/sp-debug-derive"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[lib]

[features]
default = ["std"]
std = []
force-debug = []
