[package]
name = "frame-support"
version = "40.1.0"
license = "Apache-2.0"
description = "Support code for the runtime."
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.array-bytes]
workspace = true

[dependencies.bitflags]
workspace = true

[dependencies.codec]
features = [
    "derive",
    "max-encoded-len",
]
workspace = true

[dependencies.environmental]
workspace = true

[dependencies.frame-metadata]
features = [
    "current",
    "unstable",
]
workspace = true

[dependencies.frame-support-procedural]
workspace = true

[dependencies.impl-trait-for-tuples]
workspace = true

[dependencies.k256]
features = ["ecdsa"]
workspace = true

[dependencies.log]
workspace = true

[dependencies.macro_magic]
workspace = true

[dependencies.paste]
workspace = true
default-features = true

[dependencies.scale-info]
features = ["derive"]
workspace = true

[dependencies.serde]
features = [
    "alloc",
    "derive",
]
workspace = true

[dependencies.serde_json]
features = ["alloc"]
workspace = true

[dependencies.sp-api]
features = ["frame-metadata"]
workspace = true

[dependencies.sp-arithmetic]
workspace = true

[dependencies.sp-core]
workspace = true

[dependencies.sp-crypto-hashing-proc-macro]
default-features = true
workspace = true

[dependencies.sp-debug-derive]
workspace = true

[dependencies.sp-genesis-builder]
workspace = true

[dependencies.sp-inherents]
workspace = true

[dependencies.sp-io]
workspace = true

[dependencies.sp-metadata-ir]
workspace = true

[dependencies.sp-runtime]
features = ["serde"]
workspace = true

[dependencies.sp-staking]
workspace = true

[dependencies.sp-state-machine]
optional = true
workspace = true

[dependencies.sp-std]
workspace = true

[dependencies.sp-tracing]
workspace = true

[dependencies.sp-trie]
workspace = true

[dependencies.sp-weights]
workspace = true

[dependencies.tt-call]
workspace = true

[features]
default = ["std"]
std = [
    "codec/std",
    "environmental/std",
    "frame-metadata/std",
    "frame-support-procedural/std",
    "k256/std",
    "log/std",
    "scale-info/std",
    "serde/std",
    "serde_json/std",
    "sp-api/std",
    "sp-arithmetic/std",
    "sp-core/std",
    "sp-debug-derive/std",
    "sp-genesis-builder/std",
    "sp-inherents/std",
    "sp-io/std",
    "sp-metadata-ir/std",
    "sp-runtime/std",
    "sp-staking/std",
    "sp-state-machine/std",
    "sp-std/std",
    "sp-tracing/std",
    "sp-trie/std",
    "sp-weights/std",
]
runtime-benchmarks = [
    "sp-runtime/runtime-benchmarks",
    "sp-staking/runtime-benchmarks",
]
try-runtime = [
    "sp-debug-derive/force-debug",
    "sp-runtime/try-runtime",
]
experimental = ["frame-support-procedural/experimental"]
no-metadata-docs = [
    "frame-support-procedural/no-metadata-docs",
    "sp-api/no-metadata-docs",
]
full-metadata-docs = ["scale-info/docs"]
tuples-96 = ["frame-support-procedural/tuples-96"]
tuples-128 = ["frame-support-procedural/tuples-128"]
