[package]
description = "Substrate light network protocol"
name = "sc-network-light"
version = "0.49.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
documentation = "https://docs.rs/sc-network-light"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[build-dependencies.prost-build]
workspace = true

[dependencies.array-bytes]
workspace = true
default-features = true

[dependencies.async-channel]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true
default-features = true

[dependencies.futures]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.prost]
workspace = true

[dependencies.sc-client-api]
default-features = true
workspace = true

[dependencies.sc-network-types]
default-features = true
workspace = true

[dependencies.sc-network]
default-features = true
workspace = true

[dependencies.sp-blockchain]
default-features = true
workspace = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.sp-runtime]
default-features = true
workspace = true

[dependencies.thiserror]
workspace = true
