[package]
name = "sp-test-primitives"
version = "2.0.0"
license = "Apache-2.0"
publish = false

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true

[dependencies.scale-info]
features = ["derive"]
workspace = true

[dependencies.serde]
features = ["derive"]
optional = true
workspace = true

[dependencies.sp-application-crypto]
workspace = true

[dependencies.sp-core]
workspace = true

[dependencies.sp-runtime]
workspace = true

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "serde/std",
    "sp-application-crypto/std",
    "sp-core/std",
    "sp-runtime/std",
]
serde = [
    "dep:serde",
    "sp-application-crypto/serde",
    "sp-core/serde",
    "sp-runtime/serde",
]
