[package]
name = "sc-chain-spec"
version = "43.0.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Substrate chain configurations."
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.array-bytes]
workspace = true
default-features = true

[dependencies.clap]
features = ["derive"]
optional = true
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true

[dependencies.docify]
workspace = true

[dependencies.memmap2]
workspace = true

[dependencies.sc-chain-spec-derive]
default-features = true
workspace = true

[dependencies.sc-client-api]
default-features = true
workspace = true

[dependencies.sc-executor]
default-features = true
workspace = true

[dependencies.sc-network]
default-features = true
workspace = true

[dependencies.sc-telemetry]
default-features = true
workspace = true

[dependencies.serde]
features = ["derive"]
workspace = true
default-features = true

[dependencies.serde_json]
workspace = true
default-features = true

[dependencies.sp-blockchain]
default-features = true
workspace = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.sp-crypto-hashing]
default-features = true
workspace = true

[dependencies.sp-genesis-builder]
default-features = true
workspace = true

[dependencies.sp-io]
workspace = true

[dependencies.sp-runtime]
default-features = true
workspace = true

[dependencies.sp-state-machine]
default-features = true
workspace = true

[dependencies.sp-tracing]
default-features = true
workspace = true
