[package]
name = "pallet-glutton"
version = "29.0.0"
license = "Apache-2.0"
description = "FRAME pallet for pushing a chain to its weight limits"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.blake2]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true

[dependencies.frame-benchmarking]
optional = true
workspace = true

[dependencies.frame-support]
workspace = true

[dependencies.frame-system]
workspace = true

[dependencies.log]
workspace = true

[dependencies.sp-inherents]
workspace = true

[dependencies.sp-io]
workspace = true

[dependencies.sp-runtime]
workspace = true

[features]
default = ["std"]
std = [
    "blake2/std",
    "codec/std",
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "log/std",
    "sp-inherents/std",
    "sp-io/std",
    "sp-runtime/std",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
    "sp-runtime/try-runtime",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]
