[package]
name = "pallet-grandpa"
version = "46.0.0"
license = "Apache-2.0"
description = "FRAME pallet for GRANDPA finality gadget"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true

[dependencies.frame-benchmarking]
optional = true
workspace = true

[dependencies.frame-support]
workspace = true

[dependencies.frame-system]
workspace = true

[dependencies.log]
workspace = true

[dependencies.pallet-authorship]
workspace = true

[dependencies.pallet-session]
workspace = true

[dependencies.sp-consensus-grandpa]
features = ["serde"]
workspace = true

[dependencies.sp-core]
features = ["serde"]
workspace = true

[dependencies.sp-io]
workspace = true

[dependencies.sp-runtime]
features = ["serde"]
workspace = true

[dependencies.sp-session]
workspace = true

[dependencies.sp-staking]
workspace = true

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "log/std",
    "pallet-authorship/std",
    "pallet-session/std",
    "sp-consensus-grandpa/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-staking/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-session/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "sp-staking/runtime-benchmarks",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
    "pallet-authorship/try-runtime",
    "pallet-session/try-runtime",
    "sp-runtime/try-runtime",
]
