[package]
name = "sc-consensus-grandpa"
version = "0.43.1"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Integration of the GRANDPA finality gadget into substrate."
documentation = "https://docs.rs/sc-consensus-grandpa"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.ahash]
workspace = true

[dependencies.array-bytes]
workspace = true
default-features = true

[dependencies.async-trait]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true
default-features = true

[dependencies.dyn-clone]
workspace = true

[dependencies.finality-grandpa]
features = ["derive-codec"]
workspace = true
default-features = true

[dependencies.fork-tree]
workspace = true
default-features = true

[dependencies.futures]
workspace = true

[dependencies.futures-timer]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.parking_lot]
workspace = true
default-features = true

[dependencies.prometheus-endpoint]
workspace = true
default-features = true

[dependencies.rand]
workspace = true
default-features = true

[dependencies.sc-chain-spec]
workspace = true
default-features = true

[dependencies.sc-client-api]
workspace = true
default-features = true

[dependencies.sc-client-db]
workspace = true
default-features = true

[dependencies.sc-consensus]
workspace = true
default-features = true

[dependencies.sc-network]
workspace = true
default-features = true

[dependencies.sc-network-common]
workspace = true
default-features = true

[dependencies.sc-network-gossip]
workspace = true
default-features = true

[dependencies.sc-network-sync]
workspace = true
default-features = true

[dependencies.sc-network-types]
workspace = true
default-features = true

[dependencies.sc-telemetry]
workspace = true
default-features = true

[dependencies.sc-transaction-pool-api]
workspace = true
default-features = true

[dependencies.sc-utils]
workspace = true
default-features = true

[dependencies.serde_json]
workspace = true
default-features = true

[dependencies.sp-api]
workspace = true
default-features = true

[dependencies.sp-application-crypto]
workspace = true
default-features = true

[dependencies.sp-arithmetic]
workspace = true
default-features = true

[dependencies.sp-blockchain]
workspace = true
default-features = true

[dependencies.sp-consensus]
workspace = true
default-features = true

[dependencies.sp-consensus-grandpa]
workspace = true
default-features = true

[dependencies.sp-core]
workspace = true
default-features = true

[dependencies.sp-crypto-hashing]
workspace = true
default-features = true

[dependencies.sp-keystore]
workspace = true
default-features = true

[dependencies.sp-runtime]
workspace = true
default-features = true

[dependencies.thiserror]
workspace = true
