[package]
name = "generate-bags"
version = "40.0.0"
license = "Apache-2.0"
description = "Bag threshold generation script for pallet-bag-list"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[lints]
workspace = true

[dependencies.frame-election-provider-support]
default-features = true
workspace = true

[dependencies.frame-support]
default-features = true
workspace = true

[dependencies.frame-system]
default-features = true
workspace = true

[dependencies.pallet-staking]
default-features = true
workspace = true

[dependencies.sp-staking]
default-features = true
workspace = true

[dependencies.chrono]
workspace = true

[dependencies.num-format]
workspace = true
