[package]
name = "sc-state-db"
version = "0.42.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "State database maintenance. Handles canonicalization and pruning in the database."
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true
default-features = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.parking_lot]
workspace = true
default-features = true
