[workspace]
resolver = "2"
members = [
    "substrate/client/allocator",
    "substrate/client/api",
    "substrate/client/authority-discovery",
    "substrate/client/basic-authorship",
    "substrate/client/block-builder",
    "substrate/client/chain-spec",
    "substrate/client/cli",
    "substrate/client/consensus/babe",
    "substrate/client/consensus/common",
    "substrate/client/consensus/epochs",
    "substrate/client/consensus/grandpa",
    "substrate/client/consensus/slots",
    "substrate/client/db",
    "substrate/client/executor",
    "substrate/client/executor/common",
    "substrate/client/executor/polkavm",
    "substrate/client/executor/wasmtime",
    "substrate/client/informant",
    "substrate/client/keystore",
    "substrate/client/network",
    "substrate/client/network-gossip",
    "substrate/client/network/common",
    "substrate/client/network/sync",
    "substrate/client/network/transactions",
    "substrate/client/network/types",
    "substrate/client/proposer-metrics",
    "substrate/client/rpc",
    "substrate/client/rpc-api",
    "substrate/client/rpc-servers",
    "substrate/client/service",
    "substrate/client/state-db",
    "substrate/client/sysinfo",
    "substrate/client/telemetry",
    "substrate/client/tracing",
    "substrate/client/tracing/proc-macro",
    "substrate/client/transaction-pool",
    "substrate/client/transaction-pool/api",
    "substrate/client/utils",
    "substrate/frame/authorship",
    "substrate/frame/babe",
    "substrate/frame/benchmarking",
    "substrate/frame/executive",
    "substrate/frame/grandpa",
    "substrate/frame/session",
    "substrate/frame/support",
    "substrate/frame/support/procedural",
    "substrate/frame/support/procedural/tools",
    "substrate/frame/support/procedural/tools/derive",
    "substrate/frame/system",
    "substrate/frame/timestamp",
    "substrate/frame/try-runtime",
    "substrate/primitives/api",
    "substrate/primitives/api/proc-macro",
    "substrate/primitives/application-crypto",
    "substrate/primitives/arithmetic",
    "substrate/primitives/authority-discovery",
    "substrate/primitives/block-builder",
    "substrate/primitives/blockchain",
    "substrate/primitives/consensus/babe",
    "substrate/primitives/consensus/common",
    "substrate/primitives/consensus/grandpa",
    "substrate/primitives/consensus/slots",
    "substrate/primitives/core",
    "substrate/primitives/crypto/hashing",
    "substrate/primitives/crypto/hashing/proc-macro",
    "substrate/primitives/database",
    "substrate/primitives/debug-derive",
    "substrate/primitives/externalities",
    "substrate/primitives/genesis-builder",
    "substrate/primitives/inherents",
    "substrate/primitives/io",
    "substrate/primitives/keyring",
    "substrate/primitives/keystore",
    "substrate/primitives/offchain",
    "substrate/primitives/panic-handler",
    "substrate/primitives/rpc",
    "substrate/primitives/runtime",
    "substrate/primitives/runtime-interface",
    "substrate/primitives/runtime-interface/proc-macro",
    "substrate/primitives/session",
    "substrate/primitives/staking",
    "substrate/primitives/state-machine",
    "substrate/primitives/std",
    "substrate/primitives/storage",
    "substrate/primitives/timestamp",
    "substrate/primitives/tracing",
    "substrate/primitives/transaction-pool",
    "substrate/primitives/trie",
    "substrate/primitives/version",
    "substrate/primitives/version/proc-macro",
    "substrate/primitives/wasm-interface",
    "substrate/primitives/weights",
    "substrate/utils/fork-tree",
    "substrate/utils/prometheus",
]

[workspace.package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://paritytech.github.io/polkadot-sdk/"
license = "GPL-3.0-only"
repository = "https://github.com/paritytech/polkadot-sdk.git"

[workspace.lints.rust.suspicious_double_ref_op]
level = "allow"
priority = 2

[workspace.lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(build_opt_level, values("3"))',
    'cfg(build_profile, values("debug", "release"))',
    "cfg(enable_alloc_error_handler)",
    "cfg(fuzzing)",
    "cfg(ignore_flaky_test)",
    "cfg(substrate_runtime)",
]

[workspace.lints.clippy.all]
level = "allow"
priority = 0

[workspace.lints.clippy.bind_instead_of_map]
level = "allow"
priority = 2

[workspace.lints.clippy.borrowed-box]
level = "allow"
priority = 2

[workspace.lints.clippy.complexity]
level = "warn"
priority = 1

[workspace.lints.clippy.correctness]
level = "warn"
priority = 1

[workspace.lints.clippy.default_constructed_unit_structs]
level = "allow"
priority = 2

[workspace.lints.clippy.derivable_impls]
level = "allow"
priority = 2

[workspace.lints.clippy.eq_op]
level = "allow"
priority = 2

[workspace.lints.clippy.erasing_op]
level = "allow"
priority = 2

[workspace.lints.clippy.extra-unused-type-parameters]
level = "allow"
priority = 2

[workspace.lints.clippy.identity-op]
level = "allow"
priority = 2

[workspace.lints.clippy.if-same-then-else]
level = "allow"
priority = 2

[workspace.lints.clippy.needless-lifetimes]
level = "allow"
priority = 2

[workspace.lints.clippy.needless_option_as_deref]
level = "allow"
priority = 2

[workspace.lints.clippy.nonminimal-bool]
level = "allow"
priority = 2

[workspace.lints.clippy.option-map-unit-fn]
level = "allow"
priority = 2

[workspace.lints.clippy.stable_sort_primitive]
level = "allow"
priority = 2

[workspace.lints.clippy.too-many-arguments]
level = "allow"
priority = 2

[workspace.lints.clippy.type_complexity]
level = "allow"
priority = 2

[workspace.lints.clippy.unit_arg]
level = "allow"
priority = 2

[workspace.lints.clippy.unnecessary_cast]
level = "allow"
priority = 2

[workspace.lints.clippy.useless_conversion]
level = "allow"
priority = 2

[workspace.lints.clippy.while_immutable_condition]
level = "allow"
priority = 2

[workspace.lints.clippy.zero-prefixed-literal]
level = "allow"
priority = 2

[workspace.dependencies]
polkavm-derive = "0.30.0"

[workspace.dependencies.Inflector]
version = "0.11.4"

[workspace.dependencies.ahash]
version = "0.8.2"

[workspace.dependencies.array-bytes]
version = "7.0.0"
default-features = false

[workspace.dependencies.async-channel]
version = "2.0.0"

[workspace.dependencies.async-trait]
version = "0.1.88"

[workspace.dependencies.asynchronous-codec]
version = "0.7.0"

[workspace.dependencies.backtrace]
version = "0.3.71"

[workspace.dependencies.bip39]
version = "2.2.0"
default-features = false

[workspace.dependencies.bitflags]
version = "1.3.2"

[workspace.dependencies.blake2]
version = "0.10.4"
default-features = false

[workspace.dependencies.blake2b_simd]
version = "1.0.2"
default-features = false

[workspace.dependencies.bounded-collections]
version = "0.3.2"
default-features = false

[workspace.dependencies.bs58]
version = "0.5.1"
default-features = false

[workspace.dependencies.byteorder]
version = "1.3.2"
default-features = false

[workspace.dependencies.bytes]
version = "1.4.0"
default-features = false

[workspace.dependencies.cfg-expr]
version = "0.20.0"

[workspace.dependencies.cfg-if]
version = "1.0"

[workspace.dependencies.chrono]
version = "0.4.31"

[workspace.dependencies.clap]
version = "4.5.13"

[workspace.dependencies.codec]
version = "3.7.5"
default-features = false
package = "parity-scale-codec"

[workspace.dependencies.console]
version = "0.16.0"

[workspace.dependencies.derive-syn-parse]
version = "0.2.0"

[workspace.dependencies.derive_more]
version = "1.0.0"
default-features = false

[workspace.dependencies.digest]
version = "0.10.3"
default-features = false

[workspace.dependencies.directories]
version = "6.0.0"

[workspace.dependencies.dyn-clone]
version = "1.0.16"

[workspace.dependencies.ed25519-dalek]
version = "2.1"
default-features = false

[workspace.dependencies.either]
version = "1.8.1"
default-features = false

[workspace.dependencies.environmental]
version = "1.1.4"
default-features = false

[workspace.dependencies.exit-future]
version = "0.2.0"

[workspace.dependencies.expander]
version = "2.0.0"

[workspace.dependencies.fdlimit]
version = "0.3.0"

[workspace.dependencies.finality-grandpa]
version = "0.16.3"
default-features = false

[workspace.dependencies.fnv]
version = "1.0.6"

[workspace.dependencies.foldhash]
version = "0.1.5"
default-features = false

[workspace.dependencies.fork-tree]
path = "substrate/utils/fork-tree"
default-features = false

[workspace.dependencies.forwarded-header-value]
version = "0.1.1"

[workspace.dependencies.frame-benchmarking]
path = "substrate/frame/benchmarking"
default-features = false

[workspace.dependencies.frame-support]
path = "substrate/frame/support"
default-features = false

[workspace.dependencies.frame-support-procedural]
path = "substrate/frame/support/procedural"
default-features = false

[workspace.dependencies.frame-support-procedural-tools]
path = "substrate/frame/support/procedural/tools"
default-features = false

[workspace.dependencies.frame-support-procedural-tools-derive]
path = "substrate/frame/support/procedural/tools/derive"
default-features = false

[workspace.dependencies.frame-system]
path = "substrate/frame/system"
default-features = false

[workspace.dependencies.frame-try-runtime]
path = "substrate/frame/try-runtime"
default-features = false

[workspace.dependencies.futures]
version = "0.3.31"

[workspace.dependencies.futures-timer]
version = "3.0.2"

[workspace.dependencies.governor]
version = "0.10.0"

[workspace.dependencies.hash-db]
version = "0.16.0"
default-features = false

[workspace.dependencies.hash256-std-hasher]
version = "0.15.2"
default-features = false

[workspace.dependencies.http]
version = "1.1"

[workspace.dependencies.http-body-util]
version = "0.1.2"
default-features = false

[workspace.dependencies.hyper]
version = "1.3.1"
default-features = false

[workspace.dependencies.impl-serde]
version = "0.5.0"
default-features = false

[workspace.dependencies.impl-trait-for-tuples]
version = "0.2.2"

[workspace.dependencies.indexmap]
version = "2.7.1"

[workspace.dependencies.integer-sqrt]
version = "0.1.2"

[workspace.dependencies.ip_network]
version = "0.4.1"

[workspace.dependencies.itertools]
version = "0.14.0"

[workspace.dependencies.jsonrpsee]
version = "0.24.10"

[workspace.dependencies.kvdb]
version = "0.13.0"

[workspace.dependencies.kvdb-memorydb]
version = "0.13.0"

[workspace.dependencies.kvdb-rocksdb]
default-features = false
version = "0.21.0"

[workspace.dependencies.libc]
version = "0.2.155"

[workspace.dependencies.libp2p]
version = "0.56.0"

[workspace.dependencies.libp2p-identity]
version = "0.2.9"

[workspace.dependencies.libp2p-kad]
version = "0.48.0"
default-features = false

[workspace.dependencies.linked-hash-map]
version = "0.5.4"

[workspace.dependencies.linked_hash_set]
version = "0.1.4"

[workspace.dependencies.linregress]
version = "0.5.1"

[workspace.dependencies.litep2p]
version = "0.13.0"
features = [
    "rsa",
    "websocket",
]

[workspace.dependencies.log]
version = "0.4.22"
default-features = false

[workspace.dependencies.macro_magic]
version = "0.6.0"

[workspace.dependencies.memory-db]
version = "0.34.0"
default-features = false

[workspace.dependencies.merlin]
version = "3.0"
default-features = false

[workspace.dependencies.multiaddr]
version = "0.18.1"

[workspace.dependencies.multihash]
version = "0.19.1"
default-features = false

[workspace.dependencies.names]
version = "0.14.0"
default-features = false

[workspace.dependencies.nohash-hasher]
version = "0.2.0"

[workspace.dependencies.num-bigint]
version = "0.4.6"
default-features = false

[workspace.dependencies.num-rational]
version = "0.4.1"

[workspace.dependencies.num-traits]
version = "0.2.17"
default-features = false

[workspace.dependencies.pallet-authorship]
path = "substrate/frame/authorship"
default-features = false

[workspace.dependencies.pallet-session]
path = "substrate/frame/session"
default-features = false

[workspace.dependencies.pallet-timestamp]
path = "substrate/frame/timestamp"
default-features = false

[workspace.dependencies.parity-db]
version = "0.5.0"

[workspace.dependencies.parking_lot]
version = "0.12.1"
default-features = false

[workspace.dependencies.partial_sort]
version = "1.0.0"

[workspace.dependencies.paste]
version = "1.0.15"
default-features = false

[workspace.dependencies.pin-project]
version = "1.1.3"

[workspace.dependencies.polkavm]
version = "0.30.0"
default-features = false

[workspace.dependencies.primitive-types]
version = "0.14.0"
default-features = false
features = ["num-traits"]

[workspace.dependencies.proc-macro-crate]
version = "3.0.0"

[workspace.dependencies.proc-macro-warning]
version = "1.0.0"
default-features = false

[workspace.dependencies.proc-macro2]
version = "1.0.86"

[workspace.dependencies.prometheus]
version = "0.14.0"
default-features = false

[workspace.dependencies.prometheus-endpoint]
path = "substrate/utils/prometheus"
default-features = false
package = "substrate-prometheus-endpoint"

[workspace.dependencies.prost]
version = "0.14.0"

[workspace.dependencies.prost-build]
version = "0.14.0"

[workspace.dependencies.quote]
version = "1.0.37"

[workspace.dependencies.rand]
version = "0.8.5"
default-features = false

[workspace.dependencies.rand_pcg]
version = "0.3.1"

[workspace.dependencies.ref-cast]
version = "1.0.23"

[workspace.dependencies.regex]
version = "1.10.2"

[workspace.dependencies.rpassword]
version = "7.0.0"

[workspace.dependencies.rustc-hash]
version = "2.0.0"

[workspace.dependencies.rustix]
version = "1.0.3"
default-features = false

[workspace.dependencies.rustversion]
version = "1.0.17"

[workspace.dependencies.sc-allocator]
path = "substrate/client/allocator"
default-features = false

[workspace.dependencies.sc-block-builder]
path = "substrate/client/block-builder"
default-features = false

[workspace.dependencies.sc-chain-spec]
path = "substrate/client/chain-spec"
default-features = false

[workspace.dependencies.sc-client-api]
path = "substrate/client/api"
default-features = false

[workspace.dependencies.sc-client-db]
path = "substrate/client/db"
default-features = false

[workspace.dependencies.sc-consensus]
path = "substrate/client/consensus/common"
default-features = false

[workspace.dependencies.sc-consensus-epochs]
path = "substrate/client/consensus/epochs"
default-features = false

[workspace.dependencies.sc-consensus-slots]
path = "substrate/client/consensus/slots"
default-features = false

[workspace.dependencies.sc-executor]
path = "substrate/client/executor"
default-features = false

[workspace.dependencies.sc-executor-common]
path = "substrate/client/executor/common"
default-features = false

[workspace.dependencies.sc-executor-polkavm]
path = "substrate/client/executor/polkavm"
default-features = false

[workspace.dependencies.sc-executor-wasmtime]
path = "substrate/client/executor/wasmtime"
default-features = false

[workspace.dependencies.sc-informant]
path = "substrate/client/informant"
default-features = false

[workspace.dependencies.sc-keystore]
path = "substrate/client/keystore"
default-features = false

[workspace.dependencies.sc-network]
path = "substrate/client/network"
default-features = false

[workspace.dependencies.sc-network-common]
path = "substrate/client/network/common"
default-features = false

[workspace.dependencies.sc-network-gossip]
path = "substrate/client/network-gossip"
default-features = false

[workspace.dependencies.sc-network-sync]
path = "substrate/client/network/sync"
default-features = false

[workspace.dependencies.sc-network-transactions]
path = "substrate/client/network/transactions"
default-features = false

[workspace.dependencies.sc-network-types]
path = "substrate/client/network/types"
default-features = false

[workspace.dependencies.sc-proposer-metrics]
path = "substrate/client/proposer-metrics"
default-features = false

[workspace.dependencies.sc-rpc]
path = "substrate/client/rpc"
default-features = false

[workspace.dependencies.sc-rpc-api]
path = "substrate/client/rpc-api"
default-features = false

[workspace.dependencies.sc-rpc-server]
path = "substrate/client/rpc-servers"
default-features = false

[workspace.dependencies.sc-service]
path = "substrate/client/service"
default-features = false

[workspace.dependencies.sc-state-db]
path = "substrate/client/state-db"
default-features = false

[workspace.dependencies.sc-sysinfo]
path = "substrate/client/sysinfo"
default-features = false

[workspace.dependencies.sc-telemetry]
path = "substrate/client/telemetry"
default-features = false

[workspace.dependencies.sc-tracing]
path = "substrate/client/tracing"
default-features = false

[workspace.dependencies.sc-tracing-proc-macro]
path = "substrate/client/tracing/proc-macro"
default-features = false

[workspace.dependencies.sc-transaction-pool]
path = "substrate/client/transaction-pool"
default-features = false

[workspace.dependencies.sc-transaction-pool-api]
path = "substrate/client/transaction-pool/api"
default-features = false

[workspace.dependencies.sc-utils]
path = "substrate/client/utils"
default-features = false

[workspace.dependencies.schnellru]
version = "0.2.3"

[workspace.dependencies.schnorrkel]
version = "0.11.4"
default-features = false

[workspace.dependencies.secrecy]
version = "0.8.0"
default-features = false

[workspace.dependencies.serde]
version = "1.0.214"
default-features = false

[workspace.dependencies.serde_json]
version = "1.0.132"
default-features = false

[workspace.dependencies.serde_with]
version = "3.12.0"
default-features = false
features = [
    "hex",
    "macros",
]

[workspace.dependencies.sha2]
version = "0.10.7"
default-features = false

[workspace.dependencies.sha3]
version = "0.10.0"
default-features = false

[workspace.dependencies.smallvec]
version = "1.11.0"
default-features = false

[workspace.dependencies.sp-api]
path = "substrate/primitives/api"
default-features = false

[workspace.dependencies.sp-api-proc-macro]
path = "substrate/primitives/api/proc-macro"
default-features = false

[workspace.dependencies.sp-application-crypto]
path = "substrate/primitives/application-crypto"
default-features = false

[workspace.dependencies.sp-arithmetic]
path = "substrate/primitives/arithmetic"
default-features = false

[workspace.dependencies.sp-authority-discovery]
path = "substrate/primitives/authority-discovery"
default-features = false

[workspace.dependencies.sp-block-builder]
path = "substrate/primitives/block-builder"
default-features = false

[workspace.dependencies.sp-blockchain]
path = "substrate/primitives/blockchain"
default-features = false

[workspace.dependencies.sp-consensus]
path = "substrate/primitives/consensus/common"
default-features = false

[workspace.dependencies.sp-consensus-babe]
path = "substrate/primitives/consensus/babe"
default-features = false

[workspace.dependencies.sp-consensus-grandpa]
path = "substrate/primitives/consensus/grandpa"
default-features = false

[workspace.dependencies.sp-consensus-slots]
path = "substrate/primitives/consensus/slots"
default-features = false

[workspace.dependencies.sp-core]
path = "substrate/primitives/core"
default-features = false

[workspace.dependencies.sp-crypto-hashing]
path = "substrate/primitives/crypto/hashing"
default-features = false

[workspace.dependencies.sp-crypto-hashing-proc-macro]
path = "substrate/primitives/crypto/hashing/proc-macro"
default-features = false

[workspace.dependencies.sp-database]
path = "substrate/primitives/database"
default-features = false

[workspace.dependencies.sp-debug-derive]
path = "substrate/primitives/debug-derive"
default-features = false

[workspace.dependencies.sp-externalities]
path = "substrate/primitives/externalities"
default-features = false

[workspace.dependencies.sp-genesis-builder]
path = "substrate/primitives/genesis-builder"
default-features = false

[workspace.dependencies.sp-inherents]
path = "substrate/primitives/inherents"
default-features = false

[workspace.dependencies.sp-io]
path = "substrate/primitives/io"
default-features = false

[workspace.dependencies.sp-keyring]
path = "substrate/primitives/keyring"
default-features = false

[workspace.dependencies.sp-keystore]
path = "substrate/primitives/keystore"
default-features = false

[workspace.dependencies.sp-panic-handler]
path = "substrate/primitives/panic-handler"
default-features = false

[workspace.dependencies.sp-rpc]
path = "substrate/primitives/rpc"
default-features = false

[workspace.dependencies.sp-runtime]
path = "substrate/primitives/runtime"
default-features = false

[workspace.dependencies.sp-runtime-interface]
path = "substrate/primitives/runtime-interface"
default-features = false

[workspace.dependencies.sp-runtime-interface-proc-macro]
path = "substrate/primitives/runtime-interface/proc-macro"
default-features = false

[workspace.dependencies.sp-session]
path = "substrate/primitives/session"
default-features = false

[workspace.dependencies.sp-staking]
path = "substrate/primitives/staking"
default-features = false

[workspace.dependencies.sp-state-machine]
path = "substrate/primitives/state-machine"
default-features = false

[workspace.dependencies.sp-std]
path = "substrate/primitives/std"
default-features = false

[workspace.dependencies.sp-storage]
path = "substrate/primitives/storage"
default-features = false

[workspace.dependencies.sp-timestamp]
path = "substrate/primitives/timestamp"
default-features = false

[workspace.dependencies.sp-tracing]
path = "substrate/primitives/tracing"
default-features = false

[workspace.dependencies.sp-transaction-pool]
path = "substrate/primitives/transaction-pool"
default-features = false

[workspace.dependencies.sp-trie]
path = "substrate/primitives/trie"
default-features = false

[workspace.dependencies.sp-version]
path = "substrate/primitives/version"
default-features = false

[workspace.dependencies.sp-version-proc-macro]
path = "substrate/primitives/version/proc-macro"
default-features = false

[workspace.dependencies.sp-wasm-interface]
path = "substrate/primitives/wasm-interface"
default-features = false

[workspace.dependencies.sp-weights]
path = "substrate/primitives/weights"
default-features = false

[workspace.dependencies.ss58-registry]
version = "1.34.0"
default-features = false

[workspace.dependencies.static_assertions]
version = "1.1.0"
default-features = false

[workspace.dependencies.strum]
version = "0.28.0"
default-features = false

[workspace.dependencies.syn]
version = "2.0.87"

[workspace.dependencies.tempfile]
version = "3.8.1"

[workspace.dependencies.thiserror]
version = "2.0.0"

[workspace.dependencies.tokio]
version = "1.45.0"
default-features = false

[workspace.dependencies.tokio-stream]
version = "0.1.14"

[workspace.dependencies.tower]
version = "0.4.13"

[workspace.dependencies.tower-http]
version = "0.5.2"

[workspace.dependencies.tracing]
version = "0.1.37"
default-features = false

[workspace.dependencies.tracing-core]
version = "0.1.32"
default-features = false

[workspace.dependencies.tracing-futures]
version = "0.2.4"

[workspace.dependencies.tracing-log]
version = "0.2.0"

[workspace.dependencies.tracing-subscriber]
version = "0.3.18"

[workspace.dependencies.trie-db]
version = "0.31.0"
default-features = false

[workspace.dependencies.trie-root]
version = "0.18.0"
default-features = false

[workspace.dependencies.tt-call]
version = "1.0.8"

[workspace.dependencies.tuplex]
version = "0.1"
default-features = false

[workspace.dependencies.twox-hash]
version = "2.0.0"
default-features = false

[workspace.dependencies.unsigned-varint]
version = "0.8.0"

[workspace.dependencies.wasmtime]
version = "43.0.0"
default-features = false

[workspace.dependencies.zeroize]
version = "1.7.0"
default-features = false

[profile.release]
opt-level = 3
panic = "unwind"

[profile.dev]
debug = "line-tables-only"

[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
codegen-units = 1
inherits = "release"
lto = true

[profile.testnet]
debug = 1
debug-assertions = true
inherits = "release"
overflow-checks = true
