[package]
name = "pallet-migrations"
version = "11.0.0"
description = "FRAME pallet to execute multi-block migrations."

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.license]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies.codec]
features = ["derive"]
workspace = true

[dependencies.frame]
workspace = true
features = ["runtime"]

[dependencies.frame-benchmarking]
optional = true
workspace = true

[dependencies.frame-support]
workspace = true

[dependencies.frame-system]
workspace = true

[dependencies.impl-trait-for-tuples]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.sp-core]
workspace = true

[dependencies.sp-io]
workspace = true

[dependencies.sp-runtime]
workspace = true

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "frame/std",
    "log/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "frame/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
    "frame/try-runtime",
    "sp-runtime/try-runtime",
]
