[package]
name = "sc-rpc"
version = "48.0.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Substrate Client RPC"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.codec]
workspace = true
default-features = true

[dependencies.futures]
workspace = true

[dependencies.jsonrpsee]
features = ["server"]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.sc-chain-spec]
default-features = true
workspace = true

[dependencies.sc-rpc-api]
default-features = true
workspace = true

[dependencies.sc-tracing]
default-features = true
workspace = true

[dependencies.sc-utils]
default-features = true
workspace = true

[dependencies.serde_json]
workspace = true
default-features = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.sp-runtime]
default-features = true
workspace = true

[dependencies.tokio]
workspace = true
default-features = true

[features]
test-helpers = []
