[package]
name = "sc-executor-polkavm"
version = "0.40.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "PolkaVM executor for Substrate"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.log]
workspace = true

[dependencies.polkavm]
workspace = true

[dependencies.sc-executor-common]
default-features = true
workspace = true

[dependencies.sp-wasm-interface]
default-features = true
workspace = true
