[package]
name = "sc-cli"
version = "0.53.1"
description = "Substrate CLI interface."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.array-bytes]
workspace = true
default-features = true

[dependencies.bip39]
workspace = true
default-features = true
features = ["rand"]

[dependencies.chrono]
workspace = true

[dependencies.clap]
features = [
    "derive",
    "string",
    "wrap_help",
]
workspace = true

[dependencies.codec]
workspace = true
default-features = true

[dependencies.fdlimit]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.itertools]
workspace = true

[dependencies.libp2p-identity]
features = [
    "ed25519",
    "peerid",
]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.names]
workspace = true

[dependencies.rand]
workspace = true
default-features = true

[dependencies.regex]
workspace = true

[dependencies.rpassword]
workspace = true

[dependencies.sc-client-api]
default-features = true
workspace = true

[dependencies.sc-client-db]
default-features = false
workspace = true

[dependencies.sc-keystore]
default-features = true
workspace = true

[dependencies.sc-network]
default-features = true
workspace = true

[dependencies.sc-service]
default-features = false
workspace = true

[dependencies.sc-telemetry]
default-features = true
workspace = true

[dependencies.sc-tracing]
default-features = true
workspace = true

[dependencies.sc-transaction-pool]
default-features = true
workspace = true

[dependencies.sc-utils]
default-features = true
workspace = true

[dependencies.serde]
workspace = true
default-features = true

[dependencies.serde_json]
workspace = true
default-features = true

[dependencies.sp-blockchain]
default-features = true
workspace = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.sp-keyring]
default-features = true
workspace = true

[dependencies.sp-keystore]
default-features = true
workspace = true

[dependencies.sp-panic-handler]
default-features = true
workspace = true

[dependencies.sp-runtime]
default-features = true
workspace = true

[dependencies.sp-version]
default-features = true
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tokio]
features = [
    "parking_lot",
    "rt-multi-thread",
    "signal",
]
workspace = true
default-features = true

[features]
default = ["rocksdb"]
rocksdb = ["sc-client-db/rocksdb"]
litep2p = ["sc-network/litep2p"]
