[package]
name = "sp-runtime-interface"
version = "30.0.0"
license = "Apache-2.0"
description = "Substrate runtime interface"
documentation = "https://docs.rs/sp-runtime-interface/"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.bytes]
workspace = true

[dependencies.codec]
features = ["bytes"]
workspace = true

[dependencies.sp-externalities]
workspace = true

[dependencies.sp-runtime-interface-proc-macro]
default-features = true
workspace = true

[dependencies.sp-std]
workspace = true

[dependencies.sp-tracing]
workspace = true

[dependencies.sp-wasm-interface]
workspace = true

[target.'cfg(all(any(target_arch = "riscv32", target_arch = "riscv64"), substrate_runtime))'.dependencies.polkavm-derive]
workspace = true
optional = true

[features]
default = ["std"]
std = [
    "bytes/std",
    "codec/std",
    "sp-externalities/std",
    "sp-std/std",
    "sp-tracing/std",
    "sp-wasm-interface/std",
]
disable_target_static_assertions = []
