[package]
name = "sp-runtime-interface-proc-macro"
version = "20.0.0"
license = "Apache-2.0"
description = "This crate provides procedural macros for usage within the context of the Substrate runtime interface."
documentation = "https://docs.rs/sp-runtime-interface-proc-macro"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies.Inflector]
workspace = true

[dependencies.expander]
workspace = true

[dependencies.proc-macro-crate]
workspace = true

[dependencies.proc-macro2]
workspace = true

[dependencies.quote]
workspace = true

[dependencies.syn]
features = [
    "extra-traits",
    "fold",
    "full",
    "visit",
]
workspace = true
