[package]
name = "substrate-test-runtime-client"
version = "2.0.0"
license = "Apache-2.0"
publish = false

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.sc-block-builder]
default-features = true
workspace = true

[dependencies.sc-client-api]
default-features = true
workspace = true

[dependencies.sc-consensus]
default-features = true
workspace = true

[dependencies.sp-api]
default-features = true
workspace = true

[dependencies.sp-blockchain]
default-features = true
workspace = true

[dependencies.sp-consensus]
default-features = true
workspace = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.sp-runtime]
default-features = true
workspace = true

[dependencies.substrate-test-client]
workspace = true

[dependencies.substrate-test-runtime]
workspace = true
