[package]
name = "substrate-state-trie-migration-rpc"
version = "43.0.0"
license = "Apache-2.0"
description = "Node-specific RPC methods for interaction with state trie migration."
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.codec]
workspace = true

[dependencies.serde]
features = ["derive"]
workspace = true
default-features = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.sp-state-machine]
default-features = true
workspace = true

[dependencies.sp-trie]
default-features = true
workspace = true

[dependencies.trie-db]
workspace = true
default-features = true

[dependencies.jsonrpsee]
features = [
    "client-core",
    "macros",
    "server-core",
]
workspace = true

[dependencies.sc-client-api]
default-features = true
workspace = true

[dependencies.sc-rpc-api]
default-features = true
workspace = true

[dependencies.sp-runtime]
default-features = true
workspace = true
