[package]
name = "sp-crypto-hashing"
version = "0.1.0"
license = "Apache-2.0"
description = "Hashing primitives."
documentation = "https://docs.rs/sp-crypto-hashing"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[lib]
bench = false

[dependencies.typenum]
version = "1"
default-features = false
features = ["const-generics"]

[dependencies.blake2]
version = "0.11.0-rc.5"
default-features = false
features = ["alloc"]

[dependencies.byteorder]
workspace = true

[dependencies.digest]
workspace = true
default-features = false
features = ["alloc"]

[dependencies.sha2]
workspace = true
default-features = false
features = ["alloc"]

[dependencies.sha3]
workspace = true
default-features = false
features = ["alloc"]

[dependencies.twox-hash]
features = ["xxhash64"]
workspace = true

[features]
default = ["std"]
std = [
    "byteorder/std",
    "twox-hash/std",
]
