[package]
name = "sp-runtime-interface-test-wasm-deprecated"
version = "2.0.0"
build = "build.rs"
license = "Apache-2.0"
publish = false

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.sp-core]
workspace = true

[dependencies.sp-io]
workspace = true

[dependencies.sp-runtime-interface]
workspace = true

[build-dependencies.substrate-wasm-builder]
optional = true
workspace = true
default-features = true

[features]
default = ["std"]
std = [
    "sp-core/std",
    "sp-io/std",
    "sp-runtime-interface/std",
    "substrate-wasm-builder",
]
