[package]
name = "polkadot-sdk-frame"
version = "0.10.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"
homepage = "https://paritytech.github.io"
description = "The single package to get you started with building frame pallets and runtimes"

[package.edition]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true

[dependencies.frame-benchmarking]
optional = true
workspace = true

[dependencies.frame-executive]
optional = true
workspace = true

[dependencies.frame-support]
workspace = true

[dependencies.frame-system]
workspace = true

[dependencies.frame-try-runtime]
optional = true
workspace = true

[dependencies.serde]
workspace = true

[dependencies.sp-api]
optional = true
workspace = true

[dependencies.sp-arithmetic]
workspace = true

[dependencies.sp-block-builder]
optional = true
workspace = true

[dependencies.sp-consensus-grandpa]
optional = true
workspace = true

[dependencies.sp-core]
workspace = true

[dependencies.sp-genesis-builder]
optional = true
workspace = true

[dependencies.sp-inherents]
optional = true
workspace = true

[dependencies.sp-io]
workspace = true

[dependencies.sp-keyring]
optional = true
workspace = true

[dependencies.sp-offchain]
optional = true
workspace = true

[dependencies.sp-runtime]
workspace = true

[dependencies.sp-storage]
optional = true
workspace = true

[dependencies.sp-transaction-pool]
optional = true
workspace = true

[dependencies.sp-version]
optional = true
workspace = true

[dependencies.log]
workspace = true

[features]
default = [
    "runtime",
    "std",
]
std = [
    "codec/std",
    "frame-benchmarking?/std",
    "frame-executive?/std",
    "frame-support/std",
    "frame-system/std",
    "frame-try-runtime?/std",
    "log/std",
    "serde/std",
    "sp-api?/std",
    "sp-arithmetic/std",
    "sp-block-builder?/std",
    "sp-consensus-grandpa?/std",
    "sp-core/std",
    "sp-genesis-builder?/std",
    "sp-inherents?/std",
    "sp-io/std",
    "sp-keyring?/std",
    "sp-offchain?/std",
    "sp-runtime/std",
    "sp-storage/std",
    "sp-transaction-pool?/std",
    "sp-version?/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]
try-runtime = [
    "frame-executive/try-runtime",
    "frame-support/try-runtime",
    "frame-system/try-runtime",
    "frame-try-runtime/try-runtime",
    "sp-runtime/try-runtime",
]
experimental = ["frame-support/experimental"]
runtime = [
    "frame-executive",
    "sp-api",
    "sp-block-builder",
    "sp-consensus-grandpa",
    "sp-genesis-builder",
    "sp-inherents",
    "sp-keyring",
    "sp-offchain",
    "sp-storage",
    "sp-transaction-pool",
    "sp-version",
]
