[package]
name = "sc-allocator"
version = "34.0.0"
license = "Apache-2.0"
description = "Collection of allocator implementations."
documentation = "https://docs.rs/sc-allocator"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.sp-wasm-interface]
default-features = true
workspace = true

[dependencies.thiserror]
workspace = true
