[package]
name = "sp-consensus"
version = "0.46.0"
license = "Apache-2.0"
description = "Common utilities for building and using consensus engines in substrate."
documentation = "https://docs.rs/sp-consensus/"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.futures]
features = ["thread-pool"]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.sp-inherents]
default-features = true
workspace = true

[dependencies.sp-runtime]
default-features = true
workspace = true

[dependencies.sp-state-machine]
default-features = true
workspace = true

[dependencies.thiserror]
workspace = true

[features]
default = []
