[package]
name = "sp-core-fuzz"
version = "0.1.0"
publish = false

[package.edition]
workspace = true

[package.metadata]
cargo-fuzz = true

[lints]
workspace = true

[dependencies.libfuzzer-sys]
workspace = true

[dependencies.regex]
workspace = true

[dependencies.sp-core]
default-features = true
workspace = true

[[bin]]
name = "fuzz_address_uri"
path = "fuzz_targets/fuzz_address_uri.rs"
test = false
doc = false
