[package]
name = "sc-storage-monitor"
version = "0.24.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Storage monitor service for substrate"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.repository]
workspace = true

[package.homepage]
workspace = true

[lints]
workspace = true

[dependencies.clap]
features = [
    "derive",
    "string",
]
workspace = true

[dependencies.fs4]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tokio]
features = ["time"]
workspace = true
default-features = true
