[package]
name = "sc-rpc-spec-v2"
version = "0.50.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Substrate RPC interface v2."
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.jsonrpsee]
workspace = true
features = [
    "client-core",
    "macros",
    "server-core",
]

[dependencies.sc-chain-spec]
default-features = true
workspace = true

[dependencies.array-bytes]
workspace = true
default-features = true

[dependencies.codec]
workspace = true
default-features = true

[dependencies.futures]
workspace = true

[dependencies.futures-util]
workspace = true

[dependencies.hex]
workspace = true
default-features = true

[dependencies.itertools]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.parking_lot]
workspace = true
default-features = true

[dependencies.prometheus-endpoint]
default-features = true
workspace = true

[dependencies.rand]
workspace = true
default-features = true

[dependencies.sc-client-api]
default-features = true
workspace = true

[dependencies.sc-rpc]
default-features = true
workspace = true

[dependencies.sc-transaction-pool-api]
default-features = true
workspace = true

[dependencies.schnellru]
workspace = true

[dependencies.serde]
workspace = true
default-features = true

[dependencies.sp-api]
default-features = true
workspace = true

[dependencies.sp-blockchain]
default-features = true
workspace = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.sp-rpc]
default-features = true
workspace = true

[dependencies.sp-runtime]
default-features = true
workspace = true

[dependencies.sp-version]
default-features = true
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tokio]
features = ["sync"]
workspace = true
default-features = true

[dependencies.tokio-stream]
features = ["sync"]
workspace = true
