[package]
name = "sc-proposer-metrics"
version = "0.17.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Basic metrics for block production."
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.prometheus-endpoint]
workspace = true
default-features = true
