[package]
name = "sp-tracing"
version = "16.0.0"
license = "Apache-2.0"
description = "Instrumentation primitives and macros for Substrate."
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
default-target = "wasm32-unknown-unknown"
features = ["with-tracing"]
targets = [
    "wasm32-unknown-unknown",
    "x86_64-unknown-linux-gnu",
]

[lints]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true

[dependencies.regex]
workspace = true
optional = true

[dependencies.tracing]
workspace = true

[dependencies.tracing-core]
workspace = true

[dependencies.tracing-subscriber]
workspace = true
optional = true
features = [
    "env-filter",
    "time",
    "tracing-log",
]

[features]
default = ["std"]
with-tracing = [
    "codec/derive",
    "codec/full",
]
std = [
    "codec/std",
    "regex",
    "tracing-core/std",
    "tracing-subscriber",
    "tracing/std",
    "with-tracing",
]
