[package]
name = "substrate-frame-rpc-system"
version = "44.0.0"
license = "Apache-2.0"
description = "FRAME's system exposed over Substrate RPC"
readme = "README.md"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.codec]
workspace = true
default-features = true

[dependencies.docify]
workspace = true

[dependencies.frame-system-rpc-runtime-api]
default-features = true
workspace = true

[dependencies.futures]
workspace = true

[dependencies.jsonrpsee]
features = [
    "client-core",
    "macros",
    "server-core",
]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.sc-rpc-api]
default-features = true
workspace = true

[dependencies.sc-transaction-pool-api]
default-features = true
workspace = true

[dependencies.sp-api]
default-features = true
workspace = true

[dependencies.sp-block-builder]
default-features = true
workspace = true

[dependencies.sp-blockchain]
default-features = true
workspace = true

[dependencies.sp-core]
default-features = true
workspace = true

[dependencies.sp-runtime]
default-features = true
workspace = true
