[package]
description = "Substrate sync network protocol"
name = "sc-network-sync"
version = "0.57.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
documentation = "https://docs.rs/sc-network-sync"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[dependencies.array-bytes]
workspace = true
default-features = true

[dependencies.async-channel]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.codec]
features = ["derive"]
workspace = true
default-features = true

[dependencies.fork-tree]
workspace = true
default-features = true

[dependencies.futures]
workspace = true

[dependencies.log]
workspace = true
default-features = true

[dependencies.prometheus-endpoint]
workspace = true
default-features = true

[dependencies.prost]
workspace = true

[dependencies.sc-client-api]
workspace = true
default-features = true

[dependencies.sc-consensus]
workspace = true
default-features = true

[dependencies.sc-network]
workspace = true
default-features = true

[dependencies.sc-network-common]
workspace = true
default-features = true

[dependencies.sc-network-types]
workspace = true
default-features = true

[dependencies.sc-utils]
workspace = true
default-features = true

[dependencies.schnellru]
workspace = true

[dependencies.smallvec]
workspace = true
default-features = true

[dependencies.sp-arithmetic]
workspace = true
default-features = true

[dependencies.sp-blockchain]
workspace = true
default-features = true

[dependencies.sp-consensus]
workspace = true
default-features = true

[dependencies.sp-core]
workspace = true
default-features = true

[dependencies.sp-runtime]
workspace = true
default-features = true

[dependencies.thiserror]
workspace = true

[dependencies.tokio]
features = [
    "macros",
    "time",
]
workspace = true
default-features = true

[dependencies.tokio-stream]
workspace = true

[build-dependencies.prost-build]
workspace = true
