name: Lint
permissions: {}

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  clippy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-26-intel, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
        with:
          persist-credentials: false

      - name: Get nightly version to use
        id: nightly
        shell: bash
        run: echo "version=$(cat .github/nightly-version)" >> $GITHUB_OUTPUT

      - name: Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Install nightly rust
        run: rustup toolchain install ${{ steps.nightly.outputs.version }} --profile minimal -t wasm32v1-none -c clippy

      - name: Run Clippy
        run: cargo +${{ steps.nightly.outputs.version }} clippy --locked --all-features --all-targets -- -D warnings -A clippy::items_after_test_module

      # Check the Git index didn't change as a result of the build process
      - name: Check the Git index is unmodified
        shell: bash
        run: |
          # Add all files so any untracked files are also considered in the difference
          git add .
          # Check there's no difference
          [ $(git diff HEAD | wc -l) -eq 0 ]

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
        with:
          persist-credentials: false

      - name: Install cargo deny
        run: cargo +1.98.1 install --locked cargo-deny --version =0.20.2

      - name: Run cargo deny
        run: |
          cargo deny -L error --all-features check --hide-inclusion-graph

          cd ./polkadot-sdk
          cargo deny -L error --all-features check -c ../deny.toml --hide-inclusion-graph --allow unresolved-workspace-dependency --allow unmaintained

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
        with:
          persist-credentials: false

      - name: Get nightly version to use
        id: nightly
        shell: bash
        run: echo "version=$(cat .github/nightly-version)" >> $GITHUB_OUTPUT

      - name: Install nightly rust
        run: rustup toolchain install ${{ steps.nightly.outputs.version }} --profile minimal -c rustfmt

      - name: Run rustfmt
        run: cargo +${{ steps.nightly.outputs.version }} fmt -- --check

  machete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
        with:
          persist-credentials: false

      - name: Verify all dependencies are in use
        run: |
          cargo +1.98.1 install --locked cargo-machete --version =0.9.2
          cargo +1.98.1 machete ./Cargo.toml
