name: Verify Artifact
permissions: {}

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  verify_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
        with:
          persist-credentials: false

      - name: Get nightly version to use
        id: nightly
        shell: bash
        run: echo "version=$(cat .github/nightly-version)" >> $GITHUB_OUTPUT

      - name: Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Install nightly rust
        run: rustup toolchain install ${{ steps.nightly.outputs.version }} --profile minimal --target wasm32v1-none

      - name: Install cargo machete
        run: cargo +1.95 install --locked cargo-machete --version =0.9.2

      - name: Run `patch.sh` and ensure the output matches the committed artifact
        run: |
          find polkadot-sdk/ -type f -exec sha256sum {} \; | sort > SHA256SUMS.committed
          rm -rf polkadot-sdk

          # Back this up as the `patch.sh` script will automatically update it
          cp Cargo.lock.polkadot-sdk Cargo.lock.polkadot-sdk.bak

          ./patch.sh

          # Compare the artifact
          # Exclude the ".git" directory from the clone, and the `Cargo.lock`, which weren't
          # committed
          find polkadot-sdk/ -type f -exec sha256sum {} \; | grep -v "polkadot-sdk/\.git/" | grep -v "polkadot-sdk/Cargo.lock" | sort > SHA256SUMS
          diff SHA256SUMS.committed SHA256SUMS

          # Compare the lock files
          diff Cargo.lock.polkadot-sdk Cargo.lock.polkadot-sdk.bak
          diff polkadot-sdk/Cargo.lock Cargo.lock.polkadot-sdk.bak

          # Running a second time should produce the exact same output, even if starting with a `polkadot-sdk` folder
          ./patch.sh --from-scratch
          diff Cargo.lock.polkadot-sdk Cargo.lock.polkadot-sdk.bak
          diff polkadot-sdk/Cargo.lock Cargo.lock.polkadot-sdk.bak
          rm polkadot-sdk/Cargo.lock
          rm -rf polkadot-sdk/.git
          find polkadot-sdk/ -type f -exec sha256sum {} \; | sort > SHA256SUMS
          diff SHA256SUMS.committed SHA256SUMS

          cd polkadot-sdk

          # Verify `frame-support` builds without `debug_assertions`
          cargo check -p frame-support --all-features --release

          # Verify `sc-network` builds without `litep2p`
          cargo check -p sc-network

          # Verify `sc-executor` builds without `polkavm`
          cargo check -p sc-executor
